language: node_js
sudo: required
dist: trusty
node_js:
  - "7.4.0"
before_install:
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y wine1.8
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono
  - sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib
install:
  - yarn
  - npm install bower -g
  - bower install
  - ./node_modules/.bin/electron-rebuild .
script:
  - ./node_modules/.bin/gulp
  - ./node_modules/.bin/build