language: node_js
sudo: required
dist: trusty
osx_image: xcode8.2
node_js:
  - "7.4.0"
befor_install:
  - brew update
  - brew install wine --without-x11
  - brew install libpng mono
  - brew install gnu-tar graphicsmagick xz
install:
  - yarn
  - npm install bower -g
  - bower install
  - ./node_modules/.bin/electron-rebuild .
script:
  - ./node_modules/.bin/gulp
  - ./node_modules/.bin/build