language: node_js
sudo: required
dist: trusty
node_js:
  - "7.4.0"
osx_image: xcode8.2
os:
  - osx
before_install:
  - brew install wine mono gnu-tar graphicsmagick xz rpm
install:
  - yarn
  - npm install bower -g
  - bower install
  - ./node_modules/.bin/electron-rebuild .
script:
  - ./node_modules/.bin/gulp
  - ./node_modules/.bin/build -mwl --x64 --publish --draft