language: node_js
sudo: required
dist: trusty
node_js:
  - "7.4.0"
before_install:
  - curl -L https://dl.bintray.com/develar/bin/7za -o /tmp/7za
  - chmod +x /tmp/7za
  - curl -L https://dl.bintray.com/develar/bin/wine.7z -o /tmp/wine.7z
  - /tmp/7za x -o/usr/local/Cellar -y /tmp/wine.7z
  - brew link --overwrite fontconfig gd gnutls jasper libgphoto2 libicns libtasn1 libusb libusb-compat little-cms2 nettle openssl sane-backends webp wine git-lfs gnu-tar dpkg xz
  - brew install freetype graphicsmagick
install:
  - yarn
  - npm install bower -g
  - node_modules/.bin/bower install
  - node_modules/.bin/electron-rebuild .
script:
  - node_modules/.bin/gulp
  - node_modules/.bin/build