language: node_js
sudo: required
dist: trusty
node_js:
  - "7.4.0"
cache: false  
osx_image: xcode8.2
os:
  - osx
before_install:
  - brew install wine --without-x11
  - brew install mono
  - brew install gnu-tar graphicsmagick xz
  - brew install rpm
install:
  - yarn
  - npm install bower -g
  - bower install
  - ./node_modules/.bin/electron-rebuild .
script:
  - ./node_modules/.bin/gulp
  - ./node_modules/.bin/build -mwl --x64